server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 5
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: false
    open-in-view: false
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        use_sql_comments: true
    database-platform: org.hibernate.dialect.H2Dialect
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true
      path: "/h2-console"
  data:
    redis:
      host: localhost
      port: 6379
level:
  root: info
  me.kbh.clinicsolution: debug