== 환자 정보 조회

operation::patient-controller-test/by-search-request-id[snippets="curl-request,path-parameters,http-request,response-fields,http-response"]
operation::patient-controller-test/by-search-request-id_patient-not-found-exception[snippets="http-response"]

== 환자 정보 목록 조회 (feat. 검색 조건)

operation::patient-controller-test/all-by-condition[snippets="curl-request,query-parameters,http-request,response-fields,http-response"]
operation::patient-controller-test/all-by-condition_method-argument-not-valid-exception[snippets="http-response"]

== 환자 정보 저장

operation::patient-controller-test/by-save-request[snippets="curl-request,http-request,response-fields,http-response"]
operation::patient-controller-test/by-save-request_method-argument-not-valid-exception[snippets="http-response"]

== 환자 정보 수정

operation::patient-controller-test/by-update-request[snippets="curl-request,http-request,response-fields,http-response"]
operation::patient-controller-test/by-update-request_method-argument-not-valid-exception[snippets="http-response"]

== 환자 정보 삭제

operation::hospital-controller-test/by-delete-request-id[snippets="curl-request,http-request,http-response"]
operation::hospital-controller-test/by-delete-request-id_hospital-business-exception[snippets="http-response"]
